version: '3'
services:
  app:
    build: .
    container_name: sbf-converter-kaius-app
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
      - 3001:3001